[versions]
kotlin = "2.2.21"
kotlinter = "5.2.0"
mockk = "1.14.6"
clikt = "5.0.3"
wiremock = "3.13.2"
slf4j = "2.0.17"
ideaext = "0.3.0"

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock" }
wiremock-jetty12 = { module = "org.wiremock:wiremock-jetty12", version.ref = "wiremock" }
wiremock-standalone = { module = "org.wiremock:wiremock-standalone", version.ref = "wiremock" }

kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version = "1.10.2" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }

arrow-stack = { module = "io.arrow-kt:arrow-stack", version = "2.2.0" }
arrow-annotations = { module = "io.arrow-kt:arrow-annotations" }
arrow-continuations = { module = "io.arrow-kt:arrow-continuations" }
arrow-atomic = { module = "io.arrow-kt:arrow-atomic" }
arrow-core = { module = "io.arrow-kt:arrow-core" }
arrow-core-retrofit = { module = "io.arrow-kt:arrow-core-retrofit" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines" }
arrow-fx-stm = { module = "io.arrow-kt:arrow-fx-stm" }
arrow-resilience = { module = "io.arrow-kt:arrow-resilience" }
arrow-optics = { module = "io.arrow-kt:arrow-optics" }
arrow-optics-reflect = { module = "io.arrow-kt:arrow-optics-reflect" }
arrow-optics-ksp-plugin = { module = "io.arrow-kt:arrow-optics-ksp-plugin" }

kotest-bom = { module = "io.kotest:kotest-bom", version = "6.0.5" }
kotest-common = { module = "io.kotest:kotest-common" }
kotest-extensions = { module = "io.kotest:kotest-extensions" }
kotest-property = { module = "io.kotest:kotest-property" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core" }
kotest-assertions-json = { module = "io.kotest:kotest-assertions-json" }
kotest-assertions-shared = { module = "io.kotest:kotest-assertions-shared" }
kotest-assertions-sql = { module = "io.kotest:kotest-assertions-sql" }
kotest-assertions-arrow = { module = "io.kotest.extensions:kotest-assertions-arrow", version = "2.0.0" }
kotest-extensions-blockhound = { module = "io.kotest:kotest-extensions-blockhound" }
kotest-extensions-htmlreporter = { module = "io.kotest:kotest-extensions-htmlreporter" }
kotest-extensions-http = { module = "io.kotest:kotest-extensions-http" }
kotest-extensions-junit5 = { module = "io.kotest:kotest-extensions-junit5" }
kotest-extensions-junitxml = { module = "io.kotest:kotest-extensions-junitxml" }
kotest-extensions-now = { module = "io.kotest:kotest-extensions-now" }
kotest-extensions-jvm = { module = "io.kotest:kotest-extensions-jvm" }
kotest-extensions-wiremock = { module = "io.kotest.extensions:kotest-extensions-wiremock", version="3.1.0" }
kotest-framework-concurrency = { module = "io.kotest:kotest-framework-concurrency" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest" }
kotest-framework-discovery = { module = "io.kotest:kotest-framework-discovery" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine" }
kotest-property-lifecycle = { module = "io.kotest:kotest-property-lifecycle" }
kotest-runner-junit4 = { module = "io.kotest:kotest-runner-junit4" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5" }
semver4j = { module = "com.github.gundy:semver4j", version = "0.16.4" }

auth0 = { module = "com.auth0:auth0", version = "2.26.0" }

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version = "1.9.0" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.9.0" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }

mockk-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-core = { module = "io.mockk:mockk-core", version.ref = "mockk" }
mockk-dsl = { module = "io.mockk:mockk-dsl", version.ref = "mockk" }

snakeyaml = { module = "org.yaml:snakeyaml", version = "2.5" }

clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
clikt-core = { module = "com.github.ajalt.clikt:clikt-core", version.ref = "clikt" }

log4j2-core = { module = "org.apache.logging.log4j:log4j-core" }
log4j2-to-slf4j = { module = "org.apache.logging.log4j:log4j-to-slf4j" }

logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.18" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
slf4j-jdk14 = { module = "org.slf4j:slf4j-jdk14", version.ref = "slf4j" }
slf4j-jcl-over-slf4j = { module = "org.slf4j:jcl-over-slf4j", version.ref = "slf4j" }
slf4j-jul-to-slf4j = { module = "org.slf4j:jul-to-slf4j", version.ref = "slf4j" }
slf4j-log4j-over-slf4j = { module = "org.slf4j:log4j-over-slf4j", version.ref = "slf4j" }

commons-logging = { module = "commons-logging:commons-logging" }
log4j = { module = "log4j:log4j" }

apache-http-core5 = { module = "org.apache.httpcomponents.core5:httpcore5", version = "5.3.6" }
apache-http-client5 = { module = "org.apache.httpcomponents.client5:httpclient5", version = "5.5.1" }

apache-commons-lang = { module = "org.apache.commons:commons-lang3", version = "3.20.0" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinter-gradle-plugin = { module = "org.jmailen.kotlinter:org.jmailen.kotlinter.gradle.plugin", version.ref = "kotlinter" }
ideaext-gradle-plugin = { module = "uk.org.lidalia.gradle.plugin:lidalia-idea-ext", version.ref = "ideaext" }

reflections = { module = "org.reflections:reflections", version = "0.10.2" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version = "3.0.4" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
taskTree = { id = "com.dorongold.task-tree", version = "4.0.1" }
versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }
ideaext = { id = "uk.org.lidalia.ideaext", version.ref = "ideaext" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version = "4.0.0" }
